CREATE TABLE IF NOT EXISTS submissions (
  id                          TEXT PRIMARY KEY,
  confirmation_number         TEXT NOT NULL,
  submitted_at                TEXT NOT NULL,
  company_name                TEXT NOT NULL,
  dba                         TEXT,
  tax_classification          TEXT NOT NULL,
  tax_classification_llc      TEXT,
  tax_classification_other    TEXT,
  exempt_payee_code           TEXT,
  exempt_fatca_code           TEXT,
  address_street              TEXT NOT NULL,
  address_apt                 TEXT,
  address_city                TEXT NOT NULL,
  address_state               TEXT NOT NULL,
  address_zip                 TEXT NOT NULL,
  tin_type                    TEXT NOT NULL,
  tin_encrypted               TEXT NOT NULL,
  tin_last4                   TEXT NOT NULL,
  accounting_name             TEXT NOT NULL,
  accounting_phone            TEXT NOT NULL,
  accounting_email            TEXT NOT NULL,
  remit_same_as_company       BOOLEAN NOT NULL,
  remit_street                TEXT,
  remit_city                  TEXT,
  remit_state                 TEXT,
  remit_zip                   TEXT,
  sales_name                  TEXT,
  sales_phone                 TEXT,
  sales_email                 TEXT,
  special_notes               TEXT,
  bank_name                   TEXT NOT NULL,
  bank_account_name           TEXT NOT NULL,
  bank_address_street         TEXT NOT NULL,
  bank_address_city           TEXT NOT NULL,
  bank_address_state          TEXT NOT NULL,
  bank_address_zip            TEXT NOT NULL,
  bank_account_number_encrypted TEXT NOT NULL,
  bank_account_last4          TEXT NOT NULL,
  bank_routing_number         TEXT NOT NULL,
  payment_notification_email  TEXT NOT NULL,
  signature_name              TEXT NOT NULL,
  signature_title             TEXT NOT NULL,
  signature_phone             TEXT NOT NULL,
  signature_date              TEXT NOT NULL,
  w9_certified                BOOLEAN NOT NULL,
  ach_authorized              BOOLEAN NOT NULL,
  status                      TEXT NOT NULL DEFAULT 'Pending Review',
  internal_notes              TEXT
);
